name: Terraform Plan (sandbox)

on:
  pull_request:
    paths:
      - 'envs/sandbox/**'
      - 'modules/**'
      - '.github/workflows/terraform-plan.yml'
  workflow_dispatch: {}

jobs:
  plan-sandbox-vpc:
    runs-on: ubuntu-latest

    # All commands below run from this directory
    defaults:
      run:
        working-directory: envs/sandbox/vpc-demo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.10.5'

      # Configure AWS credentials FOR THIS JOB
      # We configure a profile named "sandbox" so it matches your Terraform provider/backend
      - name: Configure AWS sandbox profile
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }} --profile sandbox
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }} --profile sandbox
          aws configure set region eu-west-1 --profile sandbox

      - name: Terraform fmt
        run: terraform fmt -check

      - name: Terraform init
        run: terraform init -input=false

      - name: Terraform validate
        run: terraform validate

      - name: Terraform plan
        run: terraform plan -input=false
